### PR TITLE
Fig 2.9 and 2.10 book2

### PR DESCRIPTION
**Pull request by TakshPanchal**
### Figure Number

Fig: 2.9 and 2.10 of Book2

### Figures

| Before PR | After PR |
| :-: | :-: |
| image |image |

### Issue 

#67 

## Steps

- [X] Jaxify
- [X] Latexify

## Checklist:

- [X] Performed a self-review of the code
- [X] Tested on Google Colab.

### CODE REVIEW

**Comment by nipunbatra** [comment]
I haven't looked at the code. Here is some feedback based om the figures you have provided.

Top figure

- We have three subplots. The caption say left and right. Perhaps we should clearly say: left, center and right
- We can use $\rho$ instead of `rho`
- Similarly, we can use $\nu$ instead of `dof`
- Not clear what the x-axis and y-axis are. Perhaps they need labels?
- Not clear what S and E are. 


Bottom figure

- The caption is clearly wrong?
- I don't think we need titles (Marginal ...) for the figures once we mention the quantity we are plotting as the y-labels
- Change `rho` to $\rho$

**Comment by TakshPanchal** [comment]
Updated Figure
image

**Comment by TakshPanchal** [comment]
> Not clear what the x-axis and y-axis are. Perhaps they need labels?

Actually, I am confused regarding this. As per my understanding of x and y axes, labels can simply be labelled as `x1` and `x2`. I need help here.

**Comment by TakshPanchal** [comment]
Captions in the fig. were not changed apologies for that.

**Comment by karm-patel** [comment]
@TakshPanchal 

Bottom figure
1. xlabel will be 
    a) $\Sigma_{11} $, b) $\Sigma_{22}$,  
c) $\rho$

Top figure
1. I have read some content from the book, but I'm also not sure what should be `xlabel`& `ylabel` since they are using eigenvectors and eigenvalues to make ellipse. But below line in code.

`fig.suptitle(f"Wi(dof={dof}, S), E=[9.5, -0.1; -0.1, 1.9], rho=-0.018")`

looks problematic, because there is no mention of E in text and no use of these values in code.
But my suggestion is just remove title since it's already mentioned in the caption. We may mention `S (scatter matrix)` in caption.

**Comment by TakshPanchal** [comment]
image

**Pull request merged**
