### PR TITLE
Added figure 2.3 of book2 pareto_dist_plot.ipynb

### PR DESCRIPTION
**Pull request by TakshPanchal**
### Figure Number

Figure 2.3 of Book2 - pareto_dist_plot.ipynb

### Figures

| Before PR | After PR |
| :-: | :-: |
| before | after |

### Issue 
#64 

## Steps

- [X] Latexify
- [X] Jaxify
- [x] Added interactive demo 

## Checklist:

- [X] Performed a self-review of the code
- [X] Tested on Google Colab.

### CODE REVIEW

**Comment by karm-patel** [comment]
## Figure related comments
1. `xlabel` & `ylabel` is missing, ideally you should read content related to this figure which helps you to decide these labels.
2. I think you don't need legend in 2nd subplot, since it's same as 1st one.
3. use `sns.despine()`
4. In legend you can probably replace `k = 2.00` to `k = 2` and `m = 0.10` to `m = 0.1` for all 4 legend's labels. This will make shorted legend labels.

**Comment by karm-patel** [comment]
Code looks good to me!

**Comment by TakshPanchal** [comment]
> ## Figure related comments
> 1. `xlabel` & `ylabel` is missing, ideally you should read content related to this figure which helps you to decide these labels.
> 2. I think you don't need legend in 2nd subplot, since it's same as 1st one.
> 3. use `sns.despine()`
> 4. In legend you can probably replace `k = 2.00` to `k = 2` and `m = 0.10` to `m = 0.1` for all 4 legend's labels. This will make shorted legend labels.

In every figure first I try to replicate the figure in the book, so from the next time should I always `despine` the graph and add axes labels to all future figs? I think types of common things will save time?

**Comment by karm-patel** [comment]
> > ## Figure related comments
> > 
> > 1. `xlabel` & `ylabel` is missing, ideally you should read content related to this figure which helps you to decide these labels.
> > 2. I think you don't need legend in 2nd subplot, since it's same as 1st one.
> > 3. use `sns.despine()`
> > 4. In legend you can probably replace `k = 2.00` to `k = 2` and `m = 0.10` to `m = 0.1` for all 4 legend's labels. This will make shorted legend labels.
> 
> In every figure first I try to replicate the figure in the book, so from the next time should I always `despine` the graph and add axes labels to all future figs? I think types of common things will save time?

Our goal is to improve figure quality and remove ambiguity, not replicating the same figures :) So whatever things can improve the figure we should do it. You can always add up your ideas to improve figure.

**Comment by TakshPanchal** [comment]
Updated figure
image

**Comment by patel-zeel** [comment]
@TakshPanchal Maybe we should consistently enable math fonts wherever suitable in legends and xlabel, ylabel. Currently, xlabel is not latexified as well as the legend.

**Comment by TakshPanchal** [comment]
I used enclosed labels in `$` sign.

**Comment by karm-patel** [comment]
@TakshPanchal, these two subplots are on different scales right? so `xlabel` should also be different? 
You can perhaps play with x-axis as log(x) and y-axis as log(p(x)) manually without using plt.loglog() to confirm your understanding.

**Comment by TakshPanchal** [comment]
Yes, I found my mistake. The X-axis scale will be in the log.

**Comment by karm-patel** [comment]
You can create a PR in main repo.

**Pull request merged**
