### PR TITLE
latexified

### PR DESCRIPTION
**Pull request by Vishal987595**
## Description
I have latexify a notebook figures.

### Figure Number
book2 - 17.21
book2 - 17.23
book2 - 17.24

### Figures
|Fig no|Before PR|After PR|After Suggestion|
|--|--|--|--|
|17.21|before17 21|final_17 21|final_17 21|
|17.23|before17 23|final_17 22|final_17 24|
|17.24|before17 24|final_17 23|final_17 25|

## Checklist:
- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

### CODE REVIEW

**Comment by nipunbatra** [comment]
17.21 looks good.

For 17.22 and 23 can we try to get them in a single row (1 X 4) instead of (2 X 2). You can use `sharey=True` to save some horizontal space. If the legend is interfering when you make the size smaller, you can have a common legend 


See: https://matplotlib.org/2.0.2/examples/pylab_examples/figlegend_demo.html and https://stackoverflow.com/questions/9834452/how-do-i-make-a-single-legend-for-many-subplots-with-matplotlib

**Comment by Vishal987595** [comment]
After trying out putting up a common legend for all figures in a single row. I found out latexifying it missing out xlabel. 
I removed the title of figures but it had no effect on the xlabel removal.

**Comment by nipunbatra** [comment]
@Vishal987595 above set of pics after suggestions look mostly fine to me. Though they seem very tall. You can reduce the fig height.

**Comment by karm-patel** [comment]
Comments 
1. Fig 17.21 currently `X1` & `Task3` are very close, I think you can have a common 2 xlabels, means no need to put xlael in the first row, similarly no need to put ylabel in the second column.
2. Fig 17.23 & 17.24: Fig height=1.5 in should look good. Can you try that, currently it is 2 in.
3.  Currently in notebooks, the above two figures, look very tall, you can use `is_latexify_enabled()` to fix this.

image

**Comment by Vishal987595** [comment]
Done edit

**Comment by karm-patel** [comment]
@Vishal987595  Great, go for PR.

**Pull request merged**
