### PR TITLE
latexify and jaxify fig 2.15 of book2

### PR DESCRIPTION
**Pull request by TakshPanchal**
### Figure Number

Fig 2.15 of book2

### Images

| Before PR | After PR |
| :-: | :-: |
|  | image

### Issue 

#98

## Steps

- [X] Latexify
- [X] Jaxify 

## Checklist:

- [X] Performed a self-review of the code
- [x] Tested on Google Colab.

## Potential problems/Important remarks
The current version of [ecdf_sample.ipynb](https://github.com/probml/pyprobml/blob/master/notebooks/book2/02/ecdf_sample.ipynb) has generated all 9 subfigures as well as a single figure of all 9 subfigs. I also generated the same but used a single figure in the image.

Also, there is a warning for `WARNING:root:The use of check_types is deprecated and does not have any effect.`

### CODE REVIEW

**Comment by karm-patel** [comment]
Plot1 does not match with old plot1. Probably you need to fix `ylim`?

**Comment by TakshPanchal** [comment]
Yes, you are right! I misunderstood. I will change it.

**Comment by karm-patel** [comment]
Hey @TakshPanchal, have you created PR of this figure in main repo?

**Comment by TakshPanchal** [comment]
This is the final figure after the change. Is it good to go?
image

**Comment by karm-patel** [comment]
Yes, LGTM, you can create a PR in the main repo.

**Pull request merged**
