### PR TITLE
Fig 28.31 latexify

### PR DESCRIPTION
**Pull request by Vishal987595**
## Description
I have latexify a figure illustrating ICA on samples from 4D source signal.

### Figure Number
book2 - 28.31

### Figures

| Before PR | After PR | After edits |
|--|--|--|
|beforePR|final|after_edit|

### Issue 
#109
## Checklist:

- [x] Performed a self-review of the code
- [x] Tested on Google Colab.

## Important remarks
The current fig_height is 1.5. On further reducing it, the yticks overlaps.

### CODE REVIEW

**Comment by karm-patel** [comment]
@Vishal987595 
1. You can remove the title and add those labels in sub-caption like (a) Truth (b) Observed Signal .... This way we can save some height.
2. Currently figures (b) & (d) are not matching with old figures, spend little time debugging it, You can probably see Matlab code, if you cannot reproduce it then we will ask Dr. Kevin while creating the PR.

**Comment by karm-patel** [comment]
@Vishal987595, What is status of this PR?

**Comment by patel-zeel** [comment]
@karm-patel I think (b) is generated by adding some noise to it so we will not be able to exactly recover that. WDYT?

**Comment by karm-patel** [comment]
> @karm-patel I think (b) is generated by adding some noise to it so we will not be able to exactly recover that. WDYT?

yes right, It looks like all plots depend on seed.
(a) & (b) are using `rand` function
(c) & (d) are using `random_srate` .

I suggested @Vishal987595 create a PR in the main repo.

**Comment by karm-patel** [comment]
> I have fixed the random_states for (c) and (d). Now figure is reproducible.

Cool, create a PR in the main repo.

**Pull request merged**
